import fs from 'node:fs';
import path from 'node:path';
import type { DailyBank, Level, Manifest } from '@ctd/core';

export const ROOT = path.resolve(import.meta.dirname, '../../..');
export const LEVELS_DIR = path.join(ROOT, 'levels');

/** Pretty JSON with coordinate pairs and cell lists kept on one line. */
export function formatJson(value: unknown): string {
  return (
    JSON.stringify(value, null, 2)
      .replace(/\[\s+(-?\d+),\s+(-?\d+)\s+\]/g, '[$1, $2]')
      .replace(/\[\s+((?:\[-?\d+, -?\d+\],?\s*)+)\]/g, (_, inner: string) => `[${inner.replace(/\s+/g, ' ').trim()}]`)
      .replace(/\[\s+((?:-?\d+(?:\.\d+)?,?\s*)+)\]/g, (_, inner: string) => `[${inner.replace(/\s+/g, ' ').trim()}]`) + '\n'
  );
}

export function writeJson(file: string, value: unknown): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, formatJson(value));
}

export function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(file, 'utf8')) as T;
}

export const pad = (n: number, w = 2) => String(n).padStart(w, '0');
export const levelId = (pack: number, index: number) => `p${pad(pack)}-l${pad(index, 3)}`;
export const levelFile = (pack: number, index: number) =>
  path.join(LEVELS_DIR, `pack-${pad(pack)}`, `level-${pad(index, 3)}.json`);

/** Regenerates levels/index.ts with static imports (Metro cannot require dynamically). */
export function writeIndex(): void {
  const manifest = readJson<Manifest>(path.join(LEVELS_DIR, 'manifest.json'));
  const lines: string[] = [
    '// AUTO-GENERATED by `npm run levelgen index`. Do not edit.',
    "import type { DailyBank, Level, Manifest } from '@ctd/core';",
    "import manifestJson from './manifest.json';",
  ];
  const entries: string[] = [];
  for (const pack of manifest.packs) {
    pack.levels.forEach((id, i) => {
      const v = id.replace('-', '_');
      const rel = `./pack-${pad(pack.id)}/level-${pad(i + 1, 3)}.json`;
      if (!fs.existsSync(path.join(LEVELS_DIR, rel))) return;
      lines.push(`import ${v} from '${rel}';`);
      entries.push(`  '${id}': ${v} as unknown as Level,`);
    });
  }
  const dailyDir = path.join(LEVELS_DIR, 'daily');
  const months = fs.existsSync(dailyDir)
    ? fs.readdirSync(dailyDir).filter((f) => /^\d{4}-\d{2}\.json$/.test(f)).sort()
    : [];
  const dailyEntries: string[] = [];
  for (const f of months) {
    const month = f.replace('.json', '');
    const v = `daily_${month.replace('-', '_')}`;
    lines.push(`import ${v} from './daily/${f}';`);
    dailyEntries.push(`  '${month}': ${v} as unknown as DailyBank,`);
  }
  lines.push(
    '',
    'export const manifest = manifestJson as Manifest;',
    '',
    'export const levels: Record<string, Level> = {',
    ...entries,
    '};',
    '',
    'export const dailyBanks: Record<string, DailyBank> = {',
    ...dailyEntries,
    '};',
    '',
  );
  fs.writeFileSync(path.join(LEVELS_DIR, 'index.ts'), lines.join('\n'));
}

export function listLevelFiles(dir: string): string[] {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) {
        if (e.name !== 'schema') walk(p);
      }
      else if (e.name.endsWith('.json') && e.name !== 'manifest.json' && e.name !== 'package.json') out.push(p);
    }
  };
  walk(dir);
  return out.sort();
}

export function loadLevelsFromFile(file: string): Level[] {
  const data = readJson<Level | DailyBank>(file);
  if ('days' in data) return Object.values(data.days).flatMap((day) => Object.values(day));
  return [data as Level];
}
