// AUTO-GENERATED by `npm run levelgen index`. Do not edit.
import type { DailyBank, Level, Manifest } from '@ctd/core';
import manifestJson from './manifest.json';
import p01_l001 from './pack-01/level-001.json';
import p01_l002 from './pack-01/level-002.json';
import p01_l003 from './pack-01/level-003.json';
import p01_l004 from './pack-01/level-004.json';
import p01_l005 from './pack-01/level-005.json';
import p01_l006 from './pack-01/level-006.json';
import p01_l007 from './pack-01/level-007.json';
import p01_l008 from './pack-01/level-008.json';
import p01_l009 from './pack-01/level-009.json';
import p01_l010 from './pack-01/level-010.json';
import p01_l011 from './pack-01/level-011.json';
import p01_l012 from './pack-01/level-012.json';
import p01_l013 from './pack-01/level-013.json';
import p01_l014 from './pack-01/level-014.json';
import p01_l015 from './pack-01/level-015.json';
import p01_l016 from './pack-01/level-016.json';
import p01_l017 from './pack-01/level-017.json';
import p01_l018 from './pack-01/level-018.json';
import p01_l019 from './pack-01/level-019.json';
import p01_l020 from './pack-01/level-020.json';
import p02_l001 from './pack-02/level-001.json';
import p02_l002 from './pack-02/level-002.json';
import p02_l003 from './pack-02/level-003.json';
import p02_l004 from './pack-02/level-004.json';
import p02_l005 from './pack-02/level-005.json';
import p02_l006 from './pack-02/level-006.json';
import p02_l007 from './pack-02/level-007.json';
import p02_l008 from './pack-02/level-008.json';
import p02_l009 from './pack-02/level-009.json';
import p02_l010 from './pack-02/level-010.json';
import p02_l011 from './pack-02/level-011.json';
import p02_l012 from './pack-02/level-012.json';
import p02_l013 from './pack-02/level-013.json';
import p02_l014 from './pack-02/level-014.json';
import p02_l015 from './pack-02/level-015.json';
import p02_l016 from './pack-02/level-016.json';
import p02_l017 from './pack-02/level-017.json';
import p02_l018 from './pack-02/level-018.json';
import p02_l019 from './pack-02/level-019.json';
import p02_l020 from './pack-02/level-020.json';
import p03_l001 from './pack-03/level-001.json';
import p03_l002 from './pack-03/level-002.json';
import p03_l003 from './pack-03/level-003.json';
import p03_l004 from './pack-03/level-004.json';
import p03_l005 from './pack-03/level-005.json';
import p03_l006 from './pack-03/level-006.json';
import p03_l007 from './pack-03/level-007.json';
import p03_l008 from './pack-03/level-008.json';
import p03_l009 from './pack-03/level-009.json';
import p03_l010 from './pack-03/level-010.json';
import p03_l011 from './pack-03/level-011.json';
import p03_l012 from './pack-03/level-012.json';
import p03_l013 from './pack-03/level-013.json';
import p03_l014 from './pack-03/level-014.json';
import p03_l015 from './pack-03/level-015.json';
import p03_l016 from './pack-03/level-016.json';
import p03_l017 from './pack-03/level-017.json';
import p03_l018 from './pack-03/level-018.json';
import p03_l019 from './pack-03/level-019.json';
import p03_l020 from './pack-03/level-020.json';
import p04_l001 from './pack-04/level-001.json';
import p04_l002 from './pack-04/level-002.json';
import p04_l003 from './pack-04/level-003.json';
import p04_l004 from './pack-04/level-004.json';
import p04_l005 from './pack-04/level-005.json';
import p04_l006 from './pack-04/level-006.json';
import p04_l007 from './pack-04/level-007.json';
import p04_l008 from './pack-04/level-008.json';
import p04_l009 from './pack-04/level-009.json';
import p04_l010 from './pack-04/level-010.json';
import p04_l011 from './pack-04/level-011.json';
import p04_l012 from './pack-04/level-012.json';
import p04_l013 from './pack-04/level-013.json';
import p04_l014 from './pack-04/level-014.json';
import p04_l015 from './pack-04/level-015.json';
import p04_l016 from './pack-04/level-016.json';
import p04_l017 from './pack-04/level-017.json';
import p04_l018 from './pack-04/level-018.json';
import p04_l019 from './pack-04/level-019.json';
import p04_l020 from './pack-04/level-020.json';
import p05_l001 from './pack-05/level-001.json';
import p05_l002 from './pack-05/level-002.json';
import p05_l003 from './pack-05/level-003.json';
import p05_l004 from './pack-05/level-004.json';
import p05_l005 from './pack-05/level-005.json';
import p05_l006 from './pack-05/level-006.json';
import p05_l007 from './pack-05/level-007.json';
import p05_l008 from './pack-05/level-008.json';
import p05_l009 from './pack-05/level-009.json';
import p05_l010 from './pack-05/level-010.json';
import p05_l011 from './pack-05/level-011.json';
import p05_l012 from './pack-05/level-012.json';
import p05_l013 from './pack-05/level-013.json';
import p05_l014 from './pack-05/level-014.json';
import p05_l015 from './pack-05/level-015.json';
import p05_l016 from './pack-05/level-016.json';
import p05_l017 from './pack-05/level-017.json';
import p05_l018 from './pack-05/level-018.json';
import p05_l019 from './pack-05/level-019.json';
import p05_l020 from './pack-05/level-020.json';
import daily_2026_09 from './daily/2026-09.json';
import daily_2026_10 from './daily/2026-10.json';
import daily_2026_11 from './daily/2026-11.json';
import daily_2026_12 from './daily/2026-12.json';

export const manifest = manifestJson as Manifest;

export const levels: Record<string, Level> = {
  'p01-l001': p01_l001 as unknown as Level,
  'p01-l002': p01_l002 as unknown as Level,
  'p01-l003': p01_l003 as unknown as Level,
  'p01-l004': p01_l004 as unknown as Level,
  'p01-l005': p01_l005 as unknown as Level,
  'p01-l006': p01_l006 as unknown as Level,
  'p01-l007': p01_l007 as unknown as Level,
  'p01-l008': p01_l008 as unknown as Level,
  'p01-l009': p01_l009 as unknown as Level,
  'p01-l010': p01_l010 as unknown as Level,
  'p01-l011': p01_l011 as unknown as Level,
  'p01-l012': p01_l012 as unknown as Level,
  'p01-l013': p01_l013 as unknown as Level,
  'p01-l014': p01_l014 as unknown as Level,
  'p01-l015': p01_l015 as unknown as Level,
  'p01-l016': p01_l016 as unknown as Level,
  'p01-l017': p01_l017 as unknown as Level,
  'p01-l018': p01_l018 as unknown as Level,
  'p01-l019': p01_l019 as unknown as Level,
  'p01-l020': p01_l020 as unknown as Level,
  'p02-l001': p02_l001 as unknown as Level,
  'p02-l002': p02_l002 as unknown as Level,
  'p02-l003': p02_l003 as unknown as Level,
  'p02-l004': p02_l004 as unknown as Level,
  'p02-l005': p02_l005 as unknown as Level,
  'p02-l006': p02_l006 as unknown as Level,
  'p02-l007': p02_l007 as unknown as Level,
  'p02-l008': p02_l008 as unknown as Level,
  'p02-l009': p02_l009 as unknown as Level,
  'p02-l010': p02_l010 as unknown as Level,
  'p02-l011': p02_l011 as unknown as Level,
  'p02-l012': p02_l012 as unknown as Level,
  'p02-l013': p02_l013 as unknown as Level,
  'p02-l014': p02_l014 as unknown as Level,
  'p02-l015': p02_l015 as unknown as Level,
  'p02-l016': p02_l016 as unknown as Level,
  'p02-l017': p02_l017 as unknown as Level,
  'p02-l018': p02_l018 as unknown as Level,
  'p02-l019': p02_l019 as unknown as Level,
  'p02-l020': p02_l020 as unknown as Level,
  'p03-l001': p03_l001 as unknown as Level,
  'p03-l002': p03_l002 as unknown as Level,
  'p03-l003': p03_l003 as unknown as Level,
  'p03-l004': p03_l004 as unknown as Level,
  'p03-l005': p03_l005 as unknown as Level,
  'p03-l006': p03_l006 as unknown as Level,
  'p03-l007': p03_l007 as unknown as Level,
  'p03-l008': p03_l008 as unknown as Level,
  'p03-l009': p03_l009 as unknown as Level,
  'p03-l010': p03_l010 as unknown as Level,
  'p03-l011': p03_l011 as unknown as Level,
  'p03-l012': p03_l012 as unknown as Level,
  'p03-l013': p03_l013 as unknown as Level,
  'p03-l014': p03_l014 as unknown as Level,
  'p03-l015': p03_l015 as unknown as Level,
  'p03-l016': p03_l016 as unknown as Level,
  'p03-l017': p03_l017 as unknown as Level,
  'p03-l018': p03_l018 as unknown as Level,
  'p03-l019': p03_l019 as unknown as Level,
  'p03-l020': p03_l020 as unknown as Level,
  'p04-l001': p04_l001 as unknown as Level,
  'p04-l002': p04_l002 as unknown as Level,
  'p04-l003': p04_l003 as unknown as Level,
  'p04-l004': p04_l004 as unknown as Level,
  'p04-l005': p04_l005 as unknown as Level,
  'p04-l006': p04_l006 as unknown as Level,
  'p04-l007': p04_l007 as unknown as Level,
  'p04-l008': p04_l008 as unknown as Level,
  'p04-l009': p04_l009 as unknown as Level,
  'p04-l010': p04_l010 as unknown as Level,
  'p04-l011': p04_l011 as unknown as Level,
  'p04-l012': p04_l012 as unknown as Level,
  'p04-l013': p04_l013 as unknown as Level,
  'p04-l014': p04_l014 as unknown as Level,
  'p04-l015': p04_l015 as unknown as Level,
  'p04-l016': p04_l016 as unknown as Level,
  'p04-l017': p04_l017 as unknown as Level,
  'p04-l018': p04_l018 as unknown as Level,
  'p04-l019': p04_l019 as unknown as Level,
  'p04-l020': p04_l020 as unknown as Level,
  'p05-l001': p05_l001 as unknown as Level,
  'p05-l002': p05_l002 as unknown as Level,
  'p05-l003': p05_l003 as unknown as Level,
  'p05-l004': p05_l004 as unknown as Level,
  'p05-l005': p05_l005 as unknown as Level,
  'p05-l006': p05_l006 as unknown as Level,
  'p05-l007': p05_l007 as unknown as Level,
  'p05-l008': p05_l008 as unknown as Level,
  'p05-l009': p05_l009 as unknown as Level,
  'p05-l010': p05_l010 as unknown as Level,
  'p05-l011': p05_l011 as unknown as Level,
  'p05-l012': p05_l012 as unknown as Level,
  'p05-l013': p05_l013 as unknown as Level,
  'p05-l014': p05_l014 as unknown as Level,
  'p05-l015': p05_l015 as unknown as Level,
  'p05-l016': p05_l016 as unknown as Level,
  'p05-l017': p05_l017 as unknown as Level,
  'p05-l018': p05_l018 as unknown as Level,
  'p05-l019': p05_l019 as unknown as Level,
  'p05-l020': p05_l020 as unknown as Level,
};

export const dailyBanks: Record<string, DailyBank> = {
  '2026-09': daily_2026_09 as unknown as DailyBank,
  '2026-10': daily_2026_10 as unknown as DailyBank,
  '2026-11': daily_2026_11 as unknown as DailyBank,
  '2026-12': daily_2026_12 as unknown as DailyBank,
};
